list:
  just --list

# Runs the deno server. Will automatically restart whenever a file used by the
# server changes.
run: build
  deno run --watch -A --env-file=dev.env main.ts

# Builds everything needed by the server.
build:
  deno check client/app.ts main.ts
  ./BUILD.ts
  ninja

# Watches for changes and then rebuilds. Run both this and `just run`.
watch:
  watchexec -i build.ninja -- just build
